apiVersion: v1
kind: ConfigMap
metadata:
  name: music-recommendation-config
  namespace: music-recommendation
data:
  FLASK_ENV: "production"
  AWS_REGION: "us-east-1"
  S3_BUCKET: "music-recommendation-data-production"
  S3_KEY: "songs_500_final.csv"
  LOG_GROUP: "/ecs/music-recommendation"